# FinFlow/docker-compose.dev.yml (dev‑ориентированный по‑умолчанию)
# Используйте переменную окружения COMPOSE_PROFILES=production,
# или файл‑override docker-compose.prod.yml, чтобы запустить бота в проде.

services:
  # --------------------------------------------------------------------- #
  # Bot ‑ включается ТОЛЬКО в профиле «production»                        #
  # --------------------------------------------------------------------- #
  bot:
    build: .
    env_file: .env.prod          # в проде
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    profiles: ["production"]

  # --------------------------------------------------------------------- #
  # PostgreSQL                                                            #
  # --------------------------------------------------------------------- #
  postgres:
    image: postgres:15
    env_file: .env.dev           # ← dev‑режим по‑умолчанию
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --------------------------------------------------------------------- #
  # Redis                                                                 #
  # --------------------------------------------------------------------- #
  redis:
    image: redis:7
    env_file: .env.dev
    command: >
      sh -c 'exec redis-server --requirepass "$${REDIS_PASSWORD}"'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: