# FinFlow/docker-compose.dev.yml
# Конфигурация для разработки: запускаются PostgreSQL и Redis, бот не запускается.

services:
  # --------------------------------------------------------------------- #
  # PostgreSQL                                                            #
  # --------------------------------------------------------------------- #
  postgres:
    image: postgres:15
    env_file: .env.dev
    ports:
      - "${POSTGRES_PORT:-5433}:5432"  # Дефолт 5433 для dev
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --------------------------------------------------------------------- #
  # Redis                                                                 #
  # --------------------------------------------------------------------- #
  redis:
    image: redis:7
    env_file: .env.dev
    command: >
      sh -c 'exec redis-server --requirepass "$${REDIS_PASSWORD}"'
    ports:
      - "${REDIS_PORT:-6380}:6379"  # Дефолт 6380 для dev
    volumes:
      - redis_data_dev:/data

networks:
  dev_network:
    driver: bridge

volumes:
  pg_data_dev:
  redis_data_dev: